Controllers/BodegasController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using ProyectoRosty.Models;
using ProyectoRosty.Models.Entidades;

namespace ProyectoRosty.Controllers
{
    public class BodegasController : Controller
    {
        private readonly LibreriaContext _context;

        public BodegasController(LibreriaContext context)
        {
            _context = context;
        }
        public async Task<IActionResult> ListadoBodegas()
        {
            return View(await _context.bodegas.ToListAsync());
        }
        public IActionResult Crear()
        {
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> Crear(Bodega bodega)
        {
            if (ModelState.IsValid)
            {
                _context.Add(bodega);
                await _context.SaveChangesAsync();
                TempData["AlertMessage"] = "Producto Creado Exitosamente";
                return RedirectToAction("ListadoBodegas");
            }
            else
            {
                ModelState.AddModelError(String.Empty, "Ha ocurrido un error");
            }
            return View();
        }
        [HttpGet]
        public async Task<IActionResult> Editar(int? id)
        {
            if (id == null || _context.bodegas == null)
            {
                return NotFound();
            }

            var bodega = await _context.bodegas.FindAsync(id);
            if (bodega == null)
            {
                return NotFound();
            }
            return View(bodega);
        }

        [HttpPost]
        public async Task<IActionResult> Editar(int id, Bodega bodega)
        {
            if (id != bodega.IdProducto)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(bodega);
                    await _context.SaveChangesAsync();
                    TempData["AlertMessage"] = "Producto actualizado " +
                        "exitosamente!!!";
                    return RedirectToAction("ListadoBodegas");
                }
                catch (Exception ex)
                {

                    ModelState.AddModelError(ex.Message, "Ocurrio un error " +
                        "al actualizar");
                }
            }
            return View(bodega);
        }
        public async Task<IActionResult> Eliminar(int? id)
        {
            if (id == null || _context.bodegas == null)
            {
                return NotFound();
            }
            var bodega = await _context.bodegas
                .FirstOrDefaultAsync(n => n.IdProducto == id);

            if (bodega == null)
            {
                return NotFound();
            }
            try
            {
                _context.bodegas.Remove(bodega);
                await _context.SaveChangesAsync();
                TempData["AlertMessage"] = "Producto eliminado exitosamente";
            }
            catch (Exception ex)
            {
                ModelState.AddModelError(ex.Message, "Ocurrio un error, no se puede eliminar");

            }
            return RedirectToAction(nameof(ListadoBodegas));

        }
    }
}

Controllers/EmpleadosController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using ProyectoRosty.Models;
using ProyectoRosty.Models.Entidades;

namespace ProyectoRosty.Controllers
{
    public class EmpleadosController : Controller
    {
        private readonly LibreriaContext _context;

        public EmpleadosController(LibreriaContext context)
        {
            _context = context;
        }
        public async Task<IActionResult> ListadoEmpleados()
        {
            return View(await _context.empleados.ToListAsync());
        }
        public IActionResult Crear()
        {
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> Crear(Empleados empleados)
        {
            if (ModelState.IsValid)
            {
                _context.Add(empleados);
                await _context.SaveChangesAsync();
                TempData["AlertMessage"] = "Empleado Creado Exitosamente";
                return RedirectToAction("ListadoEmpleados");
            }
            else
            {
                ModelState.AddModelError(String.Empty, "Ha ocurrido un error");
            }
            return View();
        }
        [HttpGet]
        public async Task<IActionResult> Editar(int? id)
        {
            if (id == null || _context.empleados == null)
            {
                return NotFound();
            }

            var empleados = await _context.empleados.FindAsync(id);
            if (empleados == null)
            {
                return NotFound();
            }
            return View(empleados);
        }

        [HttpPost]
        public async Task<IActionResult> Editar(int id, Empleados empleados)
        {
            if (id != empleados.IdEmpleado)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(empleados);
                    await _context.SaveChangesAsync();
                    TempData["AlertMessage"] = "Empleado actualizado " +
                        "exitosamente!!!";
                    return RedirectToAction("ListadoEmpleados");
                }
                catch (Exception ex)
                {

                    ModelState.AddModelError(ex.Message, "Ocurrio un error " +
                        "al actualizar");
                }
            }
            return View(empleados);
        }
        public async Task<IActionResult> Eliminar(int? id)
        {
            if (id == null || _context.empleados == null)
            {
                return NotFound();
            }
            var empleados = await _context.empleados
                .FirstOrDefaultAsync(n => n.IdEmpleado == id);

            if (empleados == null)
            {
                return NotFound();
            }
            try
            {
                _context.empleados.Remove(empleados);
                await _context.SaveChangesAsync();
                TempData["AlertMessage"] = "Empleado eliminado exitosamente";
            }
            catch (Exception ex)
            {
                ModelState.AddModelError(ex.Message, "Ocurrio un error, no se puede eliminar");

            }
            return RedirectToAction(nameof(ListadoEmpleados));

        }
    }
}

Controllers/GestionesController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using ProyectoRosty.Models;
using ProyectoRosty.Models.Entidades;

namespace ProyectoRosty.Controllers
{
    public class GestionesController : Controller
    {
        private readonly LibreriaContext _context;

        public GestionesController(LibreriaContext context)
        {
            _context = context;
        }
        public async Task<IActionResult> ListadoGestiones()
        {
            return View(await _context.GestionDeGaseosas.ToListAsync());
        }
        public IActionResult Crear()
        {
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> Crear(GestionDeGaseosas gestionDeGaseosas)
        {
            if (ModelState.IsValid)
            {
                _context.Add(gestionDeGaseosas);
                await _context.SaveChangesAsync();
                TempData["AlertMessage"] = "Gestion Creada Exitosamente";
                return RedirectToAction("ListadoGestiones");
            }
            else
            {
                ModelState.AddModelError(String.Empty, "Ha ocurrido un error");
            }
            return View();
        }
        [HttpGet]
        public async Task<IActionResult> Editar(int? id)
        {
            if (id == null || _context.GestionDeGaseosas == null)
            {
                return NotFound();
            }

            var gestionDeGaseosas = await _context.GestionDeGaseosas.FindAsync(id);
            if (gestionDeGaseosas == null)
            {
                return NotFound();
            }
            return View(gestionDeGaseosas);
        }

        [HttpPost]
        public async Task<IActionResult> Editar(int id, GestionDeGaseosas gestionDeGaseosas)
        {
            if (id != gestionDeGaseosas.IdGestion)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(gestionDeGaseosas);
                    await _context.SaveChangesAsync();
                    TempData["AlertMessage"] = "Gestion actualizada " +
                        "exitosamente!!!";
                    return RedirectToAction("ListadoGestiones");
                }
                catch (Exception ex)
                {

                    ModelState.AddModelError(ex.Message, "Ocurrio un error " +
                        "al actualizar");
                }
            }
            return View(gestionDeGaseosas);
        }
        public async Task<IActionResult> Eliminar(int? id)
        {
            if (id == null || _context.GestionDeGaseosas == null)
            {
                return NotFound();
            }
            var gestionDeGaseosas = await _context.GestionDeGaseosas
                .FirstOrDefaultAsync(n => n.IdGestion == id);

            if (gestionDeGaseosas == null)
            {
                return NotFound();
            }
            try
            {
                _context.GestionDeGaseosas.Remove(gestionDeGaseosas);
                await _context.SaveChangesAsync();
                TempData["AlertMessage"] = "Gestion eliminada exitosamente";
            }
            catch (Exception ex)
            {
                ModelState.AddModelError(ex.Message, "Ocurrio un error, no se puede eliminar");

            }
            return RedirectToAction(nameof(ListadoGestiones));

        }
    }
}

Controllers/RolesController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using ProyectoRosty.Models;
using ProyectoRosty.Models.Entidades;

namespace ProyectoRosty.Controllers
{
    public class RolesController : Controller
    {
        private readonly LibreriaContext _context;

        public RolesController(LibreriaContext context)
        {
            _context = context;
        }
        public async Task<IActionResult> ListadoRoles()
        {
            return View(await _context.roles.ToListAsync());
        }
        public IActionResult Crear()
        {
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> Crear(Roles roles)
        {
            if (ModelState.IsValid)
            {
                _context.Add(roles);
                await _context.SaveChangesAsync();
                TempData["AlertMessage"] = "Rol Creado Exitosamente";
                return RedirectToAction("ListadoRoles");
            }
            else
            {
                ModelState.AddModelError(String.Empty, "Ha ocurrido un error");
            }
            return View();
        }
        [HttpGet]
        public async Task<IActionResult> Editar(int? id)
        {
            if (id == null || _context.roles == null)
            {
                return NotFound();
            }

            var roles = await _context.roles.FindAsync(id);
            if (roles == null)
            {
                return NotFound();
            }
            return View(roles);
        }

        [HttpPost]
        public async Task<IActionResult> Editar(int id, Roles roles)
        {
            if (id != roles.IdRol)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(roles);
                    await _context.SaveChangesAsync();
                    TempData["AlertMessage"] = "Rol Actualizado " +
                        "exitosamente!!!";
                    return RedirectToAction("ListadoRoles");
                }
                catch (Exception ex)
                {

                    ModelState.AddModelError(ex.Message, "Ocurrio un error " +
                        "al actualizar");
                }
            }
            return View(roles);
        }
        public async Task<IActionResult> Eliminar(int? id)
        {
            if (id == null || _context.roles == null)
            {
                return NotFound();
            }
            var roles = await _context.roles
                .FirstOrDefaultAsync(n => n.IdRol == id);

            if (roles == null)
            {
                return NotFound();
            }
            try
            {
                _context.roles.Remove(roles);
                await _context.SaveChangesAsync();
                TempData["AlertMessage"] = "Rol eliminado exitosamente";
            }
            catch (Exception ex)
            {
                ModelState.AddModelError(ex.Message, "Ocurrio un error, no se puede eliminar");

            }
            return RedirectToAction(nameof(ListadoRoles));

        }
    }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ProyectoRosty</title>
    <!-- Elimina el atributo integrity temporalmente -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css" crossorigin="anonymous" />
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/ProyectoRosty.styles.css" asp-append-version="true" />
    @await RenderSectionAsync("Éstilos", required: false)
</head>
<body style="background-image: url('/img/pol.jpeg'); background-size: contain; background-repeat: no-repeat; background-position: center center;">


    <header>
        <nav class="navbar navbar-light" style="background-color: #ffffff; box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);">
            <div class="container-fluid">
                <a class="navbar-brand text-light" href="#" style="font-size: 24px; font-family: 'Pacifico', cursive; text-shadow: 2px 2px 4px #000;">
                    <i class="fas fa-drumstick-bite" style="color: #FFD700;"></i> <span style="font-weight: bold; color: #FFD700;">Rosty Pollos</span>

                    <img src="~/img/WhatsApp Image 2024-01-23 at 10.21.45.jpeg" alt="..." height="50">
                    
                </a>

                <button class="navbar-toggler text-light" type="button" data-bs-toggle="offcanvas" data-bs-target="#offcanvasNavbar" aria-controls="offcanvasNavbar">
                    <span class="navbar-toggler-icon" style="background-color: #fff;"></span>
                </button>
                <div class="offcanvas offcanvas-end" tabindex="-1" id="offcanvasNavbar" aria-labelledby="offcanvasNavbarLabel">
                    <div class="offcanvas-header">
                        <h5 class="offcanvas-title" id="offcanvasNavbarLabel">Menú</h5>
                        <button type="button" class="btn-close" data-bs-dismiss="offcanvas" aria-label="Close"></button>
                    </div>
                    <div class="offcanvas-body">
                        <ul class="navbar-nav justify-content-end flex-grow-1 pe-3">
                            <!-- Agrega íconos a los elementos del menú -->
                            <li class="nav-item">
                                <a class="nav-link active" asp-controller="Home" asp-action="Index" style="color: #dc3545; font-family: 'Arial Black', sans-serif; text-transform: uppercase;"><i class="fas fa-home"></i> Inicio</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="#" style="color: #dc3545; font-family: 'Arial Black', sans-serif; text-transform: uppercase;"><i class="fas fa-utensils"></i> Menú</a>
                            </li>
                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle" href="#" id="offcanvasNavbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false" style="color: #dc3545; font-family: 'Arial Black', sans-serif; text-transform: uppercase;">
                                    <i class="fas fa-list"></i> Explorar Categorías
                                </a>
                                <ul class="dropdown-menu" aria-labelledby="offcanvasNavbarDropdown">
                                    <li>
                                        <a class="dropdown-item" asp-controller="Bodegas" asp-action="ListadoBodegas" style="color: #dc3545; font-family: 'Arial', sans-serif;">
                                            <ion-icon name="cube-outline"></ion-icon> Ver Productos
                                        </a>
                                    </li>
                                    <i class="fa-solid fa-cube"></i>
                                    <li><a class="dropdown-item" asp-controller="Empleados" asp-action="ListadoEmpleados" style="color: #dc3545; font-family: 'Arial', sans-serif;"><i class="fas fa-users"></i> Nuestro Equipo</a></li>
                                    <li><a class="dropdown-item" asp-controller="Gestiones" asp-action="ListadoGestiones" style="color: #dc3545; font-family: 'Arial', sans-serif;"><i class="fas fa-tasks"></i> Actividades</a></li>
                                    <li><a class="dropdown-item" asp-controller="Roles"     asp-action="ListadoRoles"     style="color: #dc3545; font-family: 'Arial', sans-serif;"><i class="fas fa-cash-register"></i> Roles</a></li>
                                    <li><hr class="dropdown-divider"></li>
                                    <li><a class="dropdown-item" asp-controller="Registros" asp-action="ListadoRegistro" style="color: #dc3545; font-family: 'Arial', sans-serif;"><i class="fas fa-cash-register"></i> Historial de Ventas</a></li>

                                </ul>
                            </li>

                            <!-- Agrega el enlace de Cerrar Sesión -->
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="CerrarSesion" style="color: #dc3545; font-family: 'Arial Black', sans-serif; text-transform: uppercase;"><i class="fas fa-sign-out-alt"></i> Cerrar Sesión</a>
                            </li>
                        </ul>
                    </div>
                </div>
            </div>
        </nav>
    </header>

    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted" style="background-color: #070705; color: #fff; padding: 10px 0;">
        <div class="container">
            &copy; 2023 - ProyectoRosty -  <a asp-area="" asp-controller="Home" asp-action="Privacy" style="color: #fff;">Privacy</a>
        </div>
    </footer>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.20.0/font/bootstrap-icons.css">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/ionicons@6.0.3/dist/css/ionicons.min.css">

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)


</body>
</html>

Views/Shared/_ModalEliminar.cshtml
@*
    For more information on enabling MVC for empty projects, visit http://go.microsoft.com/fwlink/?LinkID=397860
*@
<div class="modal fade in" id="deleteDialog" tabindex="-1" role="dialog" data-bs-backdrop="static" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header bg-blue-gradient">
                <h5 class="modal-title" id="exampleModalLabel">Borrar Registro</h5>
            </div>
            <div class="modal-body">
                <p>¿Estás seguro de querer borrar este registro?</p>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-primary" data-bs-dismiss="modal"><i class="fa fa-ban"> </i> No</button>
                <button type="button" class="btn btn-danger" id="btnYesDelete"><i class="fa fa-check-circle"> </i> Sí</button>
            </div>
        </div>
    </div>
</div>

<script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>
<script src="https://code.jquery.com/jquery-3.6.4.min.js"></script>
<script>
    var showSuccess = false;

    $(document).ready(function () {
        $("#btnYesDelete").on("click", function () {
            // Aquí deberías poner tu lógica para determinar si mostrar éxito o error
            // Por ahora, se mostrará el mensaje de éxito directamente
            showSuccess = true;

            if (showSuccess) {
                Swal.fire({
                    title: "Se eliminó correctamente",
                    text: "El registro se ha eliminado exitosamente.",
                    icon: "success"
                });
                // Aquí debes incluir tu lógica para realizar la eliminación del registro
            } else {
                Swal.fire({
                    title: "Error",
                    text: "Mensaje de error aquí",
                    icon: "error"
                });
            }

            // Cerrar el modal
            $("#deleteDialog").modal("hide");
        });
    });
</script>

Views/Shared/_MostrarModal.cshtml
@*
    For more information on enabling MVC for empty projects, visit http://go.microsoft.com/fwlink/?LinkID=397860
*@
<div class="modal fade in" tabindex="-1" role="dialog"
     data-bs-backdrop="static" id="form-modal">
    <div class="modal-dialog modal-lg" role="document">
        <div class="modal-content">
            <div class="modal-header bg-secondary">
                <h5 class="modal-title text-white"></h5>
                <button type="button" class="btn-close text-white" data-bs-dismiss=" modal" aria-label="Close">
                </button>
            </div>
            <div class="modal-body">
            </div>
        </div>
    </div>
</div>