Controllers/RegistrosController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using ProyectoRosty.Models;
using ProyectoRosty.Models.Entidades;

namespace ProyectoRosty.Controllers
{
    public class RegistrosController : Controller
    {
        private readonly LibreriaContext _context;

        public RegistrosController(LibreriaContext context)
        {
            _context = context;
        }
        public async Task<IActionResult> ListadoRegistro()
        {
            return View(await _context.RegistroDeVentas.ToListAsync());
        }
        public IActionResult Crear()
        {
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> Crear(RegistroDeVentas registroDeVentas)
        {
            if (ModelState.IsValid)
            {
                _context.Add(registroDeVentas);
                await _context.SaveChangesAsync();
                TempData["AlertMessage"] = "Registro de Venta Creado Exitosamente";
                return RedirectToAction("ListadoRegistro");
            }
            else
            {
                ModelState.AddModelError(String.Empty, "Ha ocurrido un error");
            }
            return View();
        }
        [HttpGet]
        public async Task<IActionResult> Editar(int? id)
        {
            if (id == null || _context.RegistroDeVentas == null)
            {
                return NotFound();
            }

            var registroDeVentas = await _context.RegistroDeVentas.FindAsync(id);
            if (registroDeVentas == null)
            {
                return NotFound();
            }
            return View(registroDeVentas);
        }

        [HttpPost]
        public async Task<IActionResult> Editar(int id, RegistroDeVentas registroDeVentas)
        {
            if (id != registroDeVentas.IdVenta)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(registroDeVentas);
                    await _context.SaveChangesAsync();
                    TempData["AlertMessage"] = "Registro de Venta actualizado " +
                        "exitosamente!!!";
                    return RedirectToAction("ListadoRegistro");
                }
                catch (Exception ex)
                {

                    ModelState.AddModelError(ex.Message, "Ocurrio un error " +
                        "al actualizar");
                }
            }
            return View(registroDeVentas);
        }
        public async Task<IActionResult> Eliminar(int? id)
        {
            if (id == null || _context.RegistroDeVentas == null)
            {
                return NotFound();
            }
            var registroDeVentas = await _context.RegistroDeVentas
                .FirstOrDefaultAsync(n => n.IdVenta == id);

            if (registroDeVentas == null)
            {
                return NotFound();
            }
            try
            {
                _context.RegistroDeVentas.Remove(registroDeVentas);
                await _context.SaveChangesAsync();
                TempData["AlertMessage"] = "Registro de Venta eliminado exitosamente";
            }
            catch (Exception ex)
            {
                ModelState.AddModelError(ex.Message, "Ocurrio un error, no se puede eliminar");

            }
            return RedirectToAction(nameof(ListadoRegistro));

        }
    }
}

Views/Registros/Crear.cshtml
@model ProyectoRosty.Models.Entidades.RegistroDeVentas
@{
    ViewData["title"] = "CrearRegistro";
    Layout = null;
}
<div class="col-md-12">
    <div class="card rounded" style="background-color: #adeef0;">
        <div class="card-header text-center rounded-top" style="background-color: #5fbac4;">
            <h5 class="font-italic text-uppercase" style="font-family: 'Segoe Script', cursive;"><i class="fa fa-plus-circle"></i> Agregar una nueva Venta</h5>
        </div>
        <div class="card-body text-center">
            <form asp-action="Crear">
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>

                <div class="form-group row mb-3">
                    <label for="Venta" class="col-sm-2 col-form-label" style="color: #130000;"><i class="fa fa-tag"></i> Venta</label>
                    <div class="col-sm-10">
                        <input asp-for="VentasDiarias" class="form-control rounded" placeholder="Venta" required />
                        <span asp-validation-for="VentasDiarias" class="text-danger"></span>
                    </div>
                </div>

                <div class="form-group row mb-3">
                    <label for="DetalleVenta" class="col-sm-2 col-form-label" style="color: #130000;"><i class="fa fa-shopping-cart"></i> Detalle Venta</label>
                    <div class="col-sm-10">
                        <input asp-for="DetalleVenta" class="form-control rounded" placeholder="Detalle Venta" required />
                        <span asp-validation-for="DetalleVenta" class="text-danger"></span>
                    </div>
                </div>

                <div class="form-group row mb-3">
                    <label for="FechaVenta" class="col-sm-2 col-form-label" style="color: #130000;"><i class="fa fa-dollar-sign"></i> Fecha de Venta</label>
                    <div class="col-sm-10">
                        <input asp-for="FechaDeVenta" class="form-control rounded" placeholder="Fecha de Venta" required />
                        <span asp-validation-for="FechaDeVenta" class="text-danger"></span>
                    </div>
                </div>

                <div class="form-group row mb-3">
                    <label for="TotalVenta" class="col-sm-2 col-form-label" style="color: #130000;"><i class="fa fa-calendar"></i> Total de la Venta</label>
                    <div class="col-sm-10">
                        <input asp-for="TotalVenta" class="form-control rounded" placeholder="Total de la Venta" required />
                        <span asp-validation-for="TotalVenta" class="text-danger"></span>
                    </div>
                </div>             
                <div class="card-footer rounded-bottom" style="background-color: #0000;">
                    <div class="form-group">
                        <button type="submit" class="btn btn-lg btn-outline-success btn-3d" style="margin-right: 80px;"><i class="fa fa-save"></i> Guardar</button>
                        <button type="button" class="btn btn-lg btn-outline-danger btn-3d" data-bs-dismiss="modal"><i class="fa fa-ban"></i> Cancelar</button>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>

Views/Registros/Editar.cshtml
@model ProyectoRosty.Models.Entidades.RegistroDeVentas
@{
    ViewData["title"] = "EditarRegistro";
    Layout = null;
}
<style>
    /* Button styles */
    .btn-3d {
        background: linear-gradient(to bottom, #4CAF50 0%, #45a049 100%);
        border: 1px solid #4CAF50;
        color: #fff;
        box-shadow: 0 5px 15px rgba(0, 0, 0, 0.2);
        border-radius: 5px;
        transition: background 0.3s ease;
    }

        .btn-3d:hover {
            background: linear-gradient(to bottom, #45a049 0%, #4CAF50 100%);
        }
</style>
<div class="col-md-12">
    <div class="card">
        <div class="card-header text-center">
            <h5><i class="fa fa-edit"></i> Editar Venta</h5>
        </div>
        <div class="card-body text-center">
            <form asp-action="Editar">
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <input type="hidden" asp-for="IdVenta" />

                <div class="form-group row mb-3">
                    <label for="Nombre" class="col-sm-2 col-form-label"><i class="fa fa-tag"></i> Venta</label>
                    <div class="col-sm-10">
                        <input asp-for="VentasDiarias" class="form-control" placeholder="Venta" required />
                        <span asp-validation-for="VentasDiarias" class="text-danger"></span>
                    </div>
                </div>

                <div class="form-group row mb-3">
                    <label for="DetalleVenta" class="col-sm-2 col-form-label"><i class="fa fa-shopping-cart"></i> Detelle Venta</label>
                    <div class="col-sm-10">
                        <input asp-for="DetalleVenta" class="form-control" placeholder="Detalle Venta" required />
                        <span asp-validation-for="DetalleVenta" class="number"></span>
                    </div>
                </div>

                <div class="form-group row mb-3">
                    <label for="FechaDeVenta" class="col-sm-2 col-form-label"><i class="fa fa-dollar-sign"></i> Fecha De Venta</label>
                    <div class="col-sm-10">
                        <input asp-for="FechaDeVenta" class="form-control" placeholder="Fecha De Venta" required />
                        <span asp-validation-for="FechaDeVenta" class="text-danger"></span>
                    </div>
                </div>

                <div class="form-group row mb-3">
                    <label for="TotalVenta" class="col-sm-2 col-form-label"><i class="fa fa-calendar"></i> Total Venta</label>
                    <div class="col-sm-10">
                        <input asp-for="TotalVenta" class="form-control" placeholder="Total  Venta" required />
                        <span asp-validation-for="TotalVenta" class="text-danger"></span>
                    </div>
                </div>
                <div class="card-footer">
                    <div class="form-group">
                        <button type="submit" class="btn btn-sm btn-success btn-3d"><i class="fa fa-save"></i> Guardar</button>
                        <button type="button" class="btn btn-sm btn-primary btn-3d" data-bs-dismiss="modal"><i class="fa fa-ban"></i> Cancelar</button>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>

Views/Registros/ListadoRegistro.cshtml
@model IEnumerable<ProyectoRosty.Models.Entidades.RegistroDeVentas>
@{
    ViewData["Title"] = "ListadoRegistro";
}
@if (TempData["AlertMessage"] != null)
{
    <div class="alert alert-success">
        <strong>Ok!!-----</strong>@TempData["AlertMessage"]
    </div>
}
<div class="col-md-12">
    <div class="card">
        <div class="card-header text-center bg-primary text-white">
            <h5>Listado de Ventas</h5>
        </div>
        <div class="card-body">
            <p>
                <a onclick="showInPopup('@Url.Action("Crear", "Registros", new { id = 0 }, Context.Request.Scheme)' , '')"
                   class="btn btn-sm btn-success text-white">
                    <i class="fa fa-plus-circle"></i> Agregar una nueva Venta
                </a>

            </p>
            <table id="registro" class="table table-hover table-responsive table-striped">
                <thead>
                    <tr>
                        <th scope="#">Id</th>
                        <th scope="Venta">Venta</th>
                        <th scope="Detalle Venta">Detalle de Venta</th>
                        <th scope="Fecha Venta">Fecha de Venta</th>
                        <th scope="Total Venta">Total Venta</th>
                        <th>Acciones</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in Model)
                    {
                        <tr>
                            <th scope="row">@item.IdVenta</th>
                            <td>@Html.DisplayFor(modelItem => item.VentasDiarias)</td>
                            <td>@Html.DisplayFor(modelItem => item.DetalleVenta)</td>
                            <td>@Html.DisplayFor(modelItem => item.FechaDeVenta)</td>
                            <td>@Html.DisplayFor(modelItem => item.TotalVenta)</td>
                            <td>
                                <a onclick="showInPopup('@Url.Action("Editar", "Registros", new { id = item.IdVenta }, Context.Request.Scheme)' , 'Actualizar Registro de Venta ')"
                                   class="btn btn-warning btn-sm">
                                    <i class="fa fa-pencil-alt"></i> Editar
                                </a>
                                <button data-id="@item.IdVenta"
                                        class="btn btn-danger btn-sm deleteItem"
                                        data-bs-toggle="modal"
                                        data-bs-target="#deleteDialog">
                                    <i class="fa fa-trash"></i> Eliminar
                                </button>
                            </td>
                        </tr>
                    }
                </tbody>
            </table>
        </div>
    </div>
</div>
<partial name="_MostrarModal" />
<partial name="_ModalEliminar" />

@section Scripts {
    <script src="~/js/showmodal.js"></script>
    <script src="https://cdn.datatables.net/1.13.6/js/jquery.dataTables.min.js"></script>

    <script>
        $(document).ready(function () {
            $('#registro').DataTable(
                {
                    "language": {
                        url: "https://cdn.datatables.net/plug-ins/1.11.5/i18n/es-ES.json"
                    },
                });
        });
    </script>

    <script>
        sc_deleteDialog.openModal('deleteItem', true, 'btnYesDelete', '/Registros/Eliminar/', false);
    </script>
}